version: '3.9'
services:
  envoy:
    container_name: envoy
    build:
      context: envoy
    ports:
      - 9901:9901
      - 8090:8090
    network_mode: "host"



#    depends_on:
#      backend:
#        condition: service_healthy # waiting until heathcheck of postgres is good

#  backend:
#    container_name: backend
#    build: ./backend
#    ports:
#      - "8000:8000"

#  frontend:
#    build: ./frontend
#    depends_on:
#      - backend
